repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
        files: \.py$
    -   id: trailing-whitespace
        files: \.py$
    -   id: check-ast
        files: \.py$
    -   id: check-builtin-literals
        files: \.py$
    # запрет размещения докстрингов перед кодом
    -   id: check-docstring-first
        files: \.py$
    -   id: check-case-conflict
        files: \.py$
    # запрет на коммит неразрешенных конфликтов мерджа гита
    -   id: check-merge-conflict
    # запрет коммитов в мастер и в релиз
    -   id: no-commit-to-branch
        args: [--branch=master, --branch=release]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'
    hooks:
      - id: autopep8
        args: [--in-place, --max-line-length=120, --ignore=E203]
-   repo: https://github.com/psf/black
    rev: ''
    hooks:
      - id: black
        args: [--line-length=120]
-   repo: https://github.com/PyCQA/isort
    rev: ''
    hooks:
      - id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: ''
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=W503,W504,E302,E203']
