# Generated by Django 4.1.2 on 2022-10-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True, verbose_name="published date")),
                ("votes", models.IntegerField(default=0)),
                ("is_right", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AnswerHistoryVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("text", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True, verbose_name="published date")),
                ("votes", models.IntegerField(default=0)),
                ("found_answer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionHistoryVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="qh_question", to="posts.question"
                    ),
                ),
            ],
        ),
    ]
