# Generated by Django 4.1.2 on 2022-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
