# Generated by Django 4.1.2 on 2022-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_answer_votes_question_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(related_name="tag", to="posts.tag"),
        ),
    ]
