# Generated by Django 4.1.2 on 2022-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="found_answer",
            field=models.BooleanField(default=False),
        ),
    ]
